// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908165303_DemoSeedDataAndImages")]
    partial class DemoSeedDataAndImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("CartId");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Color");

                    b.Property<string>("ColorImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ColorImageUrl");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ProductName");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProductVariantId");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_CartItems_ProductId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("CartId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CartItems_Cart_ProductVariant");

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CartItems_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Men's clothing and accessories",
                            Name = "Men"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Women's clothing and accessories",
                            Name = "Women"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Hats, belts, and more",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("IdempotencyKey");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ShippingAddress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Status");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("TotalAmount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Orders_UserId");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Status", "\"Status\" IN ('Pending','Paid','Failed','Cancelled')");

                            t.HasCheckConstraint("CK_Orders_TotalAmount", "\"TotalAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Color");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("OrderId");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ProductName");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItems_OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_OrderItems_ProductId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_OrderItems_UnitPrice", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Embedding")
                        .HasColumnType("text")
                        .HasColumnName("Embedding");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Products_CategoryId");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price", "\"Price\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "White",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A comfortable classic tee.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900&auto=format&fit=crop&q=80",
                            Name = "Classic T-Shirt",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "Blue",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic denim jeans.",
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=900&auto=format&fit=crop&q=80",
                            Name = "Denim Jeans",
                            Price = 49.50m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "Red",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light summer dress.",
                            ImageUrl = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80",
                            Name = "Summer Dress",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "Black",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable heels.",
                            ImageUrl = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&auto=format&fit=crop&q=80",
                            Name = "Heels",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Color = "Navy",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stylish cap.",
                            ImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=900&auto=format&fit=crop&q=80",
                            Name = "Baseball Cap",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Color = "Brown",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genuine leather belt.",
                            ImageUrl = "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=900&auto=format&fit=crop&q=80",
                            Name = "Leather Belt",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "Oatmeal",
                            CreatedAt = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mid-weight extra-fine Merino knit with ribbed trims — warm, breathable and not itchy.",
                            ImageUrl = "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=900&auto=format&fit=crop&q=80",
                            Name = "Merino Wool Sweater",
                            Price = 79.00m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "White",
                            CreatedAt = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Garment-washed Oxford cotton with a soft roll collar. Wears equally well tucked or open over a tee.",
                            ImageUrl = "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=900&auto=format&fit=crop&q=80",
                            Name = "Oxford Button-Down Shirt",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "Khaki",
                            CreatedAt = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stretch-cotton twill chinos with a clean tapered leg, reinforced seams and deep front pockets.",
                            ImageUrl = "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=900&auto=format&fit=crop&q=80",
                            Name = "Slim Chino Trousers",
                            Price = 58.00m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "Black",
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight water-repellent bomber with ribbed cuffs and a matte zip. Layers over knitwear all season.",
                            ImageUrl = "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=900&auto=format&fit=crop&q=80",
                            Name = "Bomber Jacket",
                            Price = 135.00m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000025"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "Blush",
                            CreatedAt = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fluid accordion-pleated midi with an elastic-back waistband for all-day comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80",
                            Name = "Pleated Midi Skirt",
                            Price = 62.00m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000026"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "Camel",
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Half-canvassed single-breasted blazer in Italian wool with natural shoulders and working cuffs.",
                            ImageUrl = "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&auto=format&fit=crop&q=80",
                            Name = "Tailored Wool Blazer",
                            Price = 168.00m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000027"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "Champagne",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bias-cut sandwashed silk slip with adjustable straps and a subtle cowl neck.",
                            ImageUrl = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80",
                            Name = "Silk Slip Dress",
                            Price = 115.00m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000028"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Color = "Grey",
                            CreatedAt = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chunky rib-knit lambswool beanie with a fold-over cuff. One size, generous fit.",
                            ImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=900&auto=format&fit=crop&q=80",
                            Name = "Ribbed Wool Beanie",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000029"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Color = "Khaki",
                            CreatedAt = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cotton-webbing belt with a brushed-metal box buckle and leather keeper. Trim to fit.",
                            ImageUrl = "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=900&auto=format&fit=crop&q=80",
                            Name = "Canvas Web Belt",
                            Price = 18.00m
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Color");

                    b.Property<string>("ColorImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ColorImageUrl");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProductId");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Size");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("StockQuantity");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Color")
                        .IsUnique()
                        .HasDatabaseName("UQ_ProductVariants_Product_Color");

                    b.ToTable("ProductVariants", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductVariants_StockQuantity", "\"StockQuantity\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000101"),
                            Color = "White",
                            ColorImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Size = "M",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000102"),
                            Color = "Black",
                            ColorImageUrl = "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Size = "L",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000103"),
                            Color = "Navy",
                            ColorImageUrl = "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Size = "S",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000201"),
                            Color = "Blue",
                            ColorImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Size = "32",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000202"),
                            Color = "Black",
                            ColorImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Size = "34",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000301"),
                            Color = "Red",
                            ColorImageUrl = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Size = "S",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000302"),
                            Color = "Blue",
                            ColorImageUrl = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Size = "M",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000303"),
                            Color = "Yellow",
                            ColorImageUrl = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Size = "S",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000401"),
                            Color = "Black",
                            ColorImageUrl = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Size = "38",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000402"),
                            Color = "Nude",
                            ColorImageUrl = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Size = "37",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000501"),
                            Color = "Navy",
                            ColorImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Size = "One Size",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000502"),
                            Color = "Black",
                            ColorImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Size = "One Size",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000503"),
                            Color = "Olive",
                            ColorImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Size = "One Size",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000601"),
                            Color = "Brown",
                            ColorImageUrl = "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Size = "M",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000602"),
                            Color = "Black",
                            ColorImageUrl = "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Size = "L",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002101"),
                            Color = "Oatmeal",
                            ColorImageUrl = "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000021"),
                            Size = "M",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002102"),
                            Color = "Charcoal",
                            ColorImageUrl = "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000021"),
                            Size = "L",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002201"),
                            Color = "White",
                            ColorImageUrl = "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000022"),
                            Size = "M",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002202"),
                            Color = "Sky Blue",
                            ColorImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000022"),
                            Size = "L",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002203"),
                            Color = "Pink",
                            ColorImageUrl = "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000022"),
                            Size = "S",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002301"),
                            Color = "Khaki",
                            ColorImageUrl = "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000023"),
                            Size = "32",
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002302"),
                            Color = "Navy",
                            ColorImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000023"),
                            Size = "34",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002303"),
                            Color = "Olive",
                            ColorImageUrl = "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000023"),
                            Size = "30",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002401"),
                            Color = "Black",
                            ColorImageUrl = "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000024"),
                            Size = "M",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002402"),
                            Color = "Olive",
                            ColorImageUrl = "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000024"),
                            Size = "L",
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002501"),
                            Color = "Blush",
                            ColorImageUrl = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000025"),
                            Size = "S",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002502"),
                            Color = "Black",
                            ColorImageUrl = "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000025"),
                            Size = "M",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002601"),
                            Color = "Camel",
                            ColorImageUrl = "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000026"),
                            Size = "M",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002602"),
                            Color = "Charcoal",
                            ColorImageUrl = "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000026"),
                            Size = "S",
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002701"),
                            Color = "Champagne",
                            ColorImageUrl = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000027"),
                            Size = "S",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002702"),
                            Color = "Emerald",
                            ColorImageUrl = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000027"),
                            Size = "M",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002703"),
                            Color = "Black",
                            ColorImageUrl = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000027"),
                            Size = "L",
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002801"),
                            Color = "Grey",
                            ColorImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000028"),
                            Size = "One Size",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002802"),
                            Color = "Black",
                            ColorImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000028"),
                            Size = "One Size",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002803"),
                            Color = "Mustard",
                            ColorImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000028"),
                            Size = "One Size",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002901"),
                            Color = "Khaki",
                            ColorImageUrl = "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000029"),
                            Size = "M",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000002902"),
                            Color = "Navy",
                            ColorImageUrl = "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=900&auto=format&fit=crop&q=80",
                            ProductId = new Guid("20000000-0000-0000-0000-000000000029"),
                            Size = "L",
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FullName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Customer")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Customer','Admin')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@souqy.local",
                            FullName = "Souqy Admin",
                            PasswordHash = "$2a$11$Fk9B2IKFSWmqiZ4/GS/BueBRgv2Qfmyoyvi38gSloHTim10ngWlU2",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nour@souqy.local",
                            FullName = "Nour Hassan",
                            PasswordHash = "$2a$11$FFNhXAkvCy20R2rbAa1mFOetTfdMbfKbb9D0ZVfvAoDRh67qBzxuC",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar@souqy.local",
                            FullName = "Omar Khaled",
                            PasswordHash = "$2a$11$FFNhXAkvCy20R2rbAa1mFOetTfdMbfKbb9D0ZVfvAoDRh67qBzxuC",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Carts_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Carts");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Products");

                    b.HasOne("Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_ProductVariants");

                    b.Navigation("Cart");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Orders");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_OrderItems_Products");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductVariants_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
